
filter:
    paths: [src/*] 

checks:
    php:
        code_rating: true
        duplication: true

tools:
    php_sim: true
    php_changetracking: true
    php_cs_fixer:
        config: { level: psr2 } 
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: false
    sensiolabs_security_checker: true
    php_code_sniffer:
        enabled: true
        config:
          standard: PSR2
    external_code_coverage: true

